/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  customizationSidebar: [
      'customization/index',
      'customization/plant',
      'customization/mutation',
      'customization/soil',
      'customization/fertilizer',
      'customization/weed',
      'customization/wrapping-up',
      'customization/tolerance-calculator',
      {
          'Other versions': {
              '1.16 & 1.18': [
                  'customization/1.18/index',
                  'customization/1.18/plant',
                  'customization/1.18/weed',
                  'customization/1.18/mutation',
                  'customization/1.18/soil',
                  'customization/1.18/fertilizer',
              ],
              '1.12': [
                  'customization/1.12/index',
                  'customization/1.12/plant',
                  'customization/1.12/mutation',
                  'customization/1.12/soil',
              ]
          }
      }
  ],
  // wikiSidebar: [{type: 'autogenerated', dirName: 'wiki'}],
  wikiSidebar: [
      'wiki/index',
      'wiki/faq',
      'wiki/mutation-calculator',
      {
          'type': 'category',
          'label': 'Blocks & Items',
          'link': {
              'type': 'generated-index',
              'title': 'Blocks & Items',
              'description': 'Learn about AgriCraft blocks and items',
              'slug': 'block-item'
          },
          'items': [
              'wiki/block-item/analyzer',
              'wiki/block-item/journal'
          ]
      }
  ],
  // docusaurusSidebar: [{type: 'autogenerated', dirName: 'docusaurus'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
