/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  customizationSidebar: [
      'customization/index',
      'customization/plant',
      'customization/mutation',
      'customization/soil',
      'customization/fertilizer',
      'customization/weed',
      'customization/wrapping-up',
      'customization/tolerance-calculator'
  ],
  // wikiSidebar: [{type: 'autogenerated', dirName: 'wiki'}],
  wikiSidebar: [
      'wiki/index',
      'wiki/faq',
      'wiki/mutation-calculator'
  ],
  // docusaurusSidebar: [{type: 'autogenerated', dirName: 'docusaurus'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
